### ISSUE TITLE
Erorr: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by DaniEnsi** [gotr00t0day/spyhunt#22]
Command: `python3 spyhunt.py -j https://yahoo.com`

Output:  
```
███████╗██████╗ ██╗   ██╗██╗  ██╗██╗   ██╗███╗   ██╗████████╗
██╔════╝██╔══██╗╚██╗ ██╔╝██║  ██║██║   ██║████╗  ██║╚══██╔══╝
███████╗██████╔╝ ╚████╔╝ ███████║██║   ██║██╔██╗ ██║   ██║
╚════██║██╔═══╝   ╚██╔╝  ██╔══██║██║   ██║██║╚██╗██║   ██║
███████║██║        ██║   ██║  ██║╚██████╔╝██║ ╚████║   ██║
╚══════╝╚═╝        ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝
V 1.10
By c0deninja



Traceback (most recent call last):
  File "/Users/dan/Documents/GitHub/spyhunt/spyhunt.py", line 513, in <module>
    endpoints = future.result()
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/spyhunter/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/spyhunter/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Caskroom/miniforge/base/envs/spyhunter/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dan/Documents/GitHub/spyhunt/spyhunt.py", line 500, in extract_endpoints
    urls = [item for item in context.eval("Object.values(this)") if isinstance(item, str) and item.startswith(('http://', 'https://'))]
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/spyhunter/lib/python3.11/site-packages/execjs/_abstract_runtime_context.py", line 27, in eval
    return self._eval(source)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/spyhunter/lib/python3.11/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/spyhunter/lib/python3.11/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/spyhunter/lib/python3.11/site-packages/execjs/_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/spyhunter/lib/python3.11/site-packages/execjs/_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: ReferenceError: window is not defined

```

**Comment by gotr00t0day** [comment]
I pushed an update, see if that works.
